collections:
    projects:
        output: true
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      parent: "/projects.html"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      parent: "/posts.html"
  - scope:
      path: ""
    values:
      layout: "default_narrow"
